This is makeindex, version 2.16 [MiKTeX 25.3].
Scanning style file ./output.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file output.acn....done (713 entries accepted, 0 rejected).
Sorting entries........done (7087 comparisons).
Generating output file output.acr....done (253 lines written, 0 warnings).
Output written in output.acr.
Transcript written in output.alg.
